matrix:
  include:
    - os: linux
      language: python
      python: 3.6
      before_install: pip3 install pipenv
      install: cd backend && pipenv install; cd -
      script: cd backend && pipenv run ./manage.py test; cd -

    - os: osx
      osx_image: xcode9.4
      before_script:
        - git clone https://github.com/flutter/flutter.git -b beta --depth 1 || cd flutter && git pull; cd -
        - cd flutter_travis_sample && ./flutter/bin/flutter doctor; cd -
        - pip install six
      script:
        - cd flutter_travis_sample && ../flutter/bin/flutter build ios && cd -
      cache:
        directories:
          - $HOME/.pub-cache

    - language: android
      android:
        components:
          # Uncomment the lines below if you want to
          # use the latest revision of Android SDK Tools
          - tools
          - platform-tools

          # The BuildTools version used by your project
          - build-tools-26.0.2

          # The SDK version used to compile your project
          - android-26

          # Specify at least one system image,
          # if you need to run emulator(s) during your tests
          - sys-img-armeabi-v7a-android-26
          - sys-img-armeabi-v7a-android-17
      before_script:
        - git clone https://github.com/flutter/flutter.git -b beta --depth 1 || cd flutter && git pull; cd -
        - cd flutter_travis_sample && ./flutter/bin/flutter doctor; cd -
      script:
        - cd flutter_travis_sample && ../flutter/bin/flutter build apk && cd -
      cache:
        directories:
          - $HOME/.pub-cache



      # os:
      #   - linux
      #   - osx
      # sudo: false
      #
      # addons:
      #   apt:
      #     # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
      #     sources:
      #       - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
      #     packages:
      #       - libstdc++6
      #       - fonts-droid
      #
      # before_script:
      #   - git clone https://github.com/flutter/flutter.git -b beta --depth 1 || cd flutter && git pull -r; cd -
      #   - ls -la
      #   - cd flutter_travis_sample && ./flutter/bin/flutter doctor; cd -
      #
      # script:
      #   - cd flutter_travis_sample && ../flutter/bin/flutter test; cd -
      #   - ls -la
      #   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd flutter_travis_sample && ../flutter/bin/flutter build apk; cd -; fi
      #   - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd flutter_travis_sample && ../flutter/bin/flutter build ios; cd -; fi
      #
      # cache:
      #   directories:
      #     - $HOME/.pub-cache
      #     - flutter
      #
