# Generated by Django 2.0.2 on 2018-02-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbsuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
