# Generated by Django 2.0.2 on 2018-02-20 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20180220_1336'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_Purchase',
            new_name='ProductPurchase',
        ),
    ]
