# Generated by Django 2.0.2 on 2018-02-20 14:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_auto_20180220_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpurchase',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='productpurchase',
            name='purchase_id',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='total_price',
            new_name='product_amount',
        ),
        migrations.AddField(
            model_name='purchase',
            name='product_id',
            field=models.ForeignKey(default='6d70317e-4677-4d7e-a71d-bc89c495ab7c', on_delete=django.db.models.deletion.DO_NOTHING, related_name='product', to='operations.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='product_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.DeleteModel(
            name='ProductPurchase',
        ),
    ]
