# Generated by Django 2.0.2 on 2019-01-19 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_auto_20190113_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='owned_by',
        ),
        migrations.RemoveField(
            model_name='bbsuser',
            name='default_account',
        ),
        migrations.AddField(
            model_name='bbsuser',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='affected_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
