name: flutter_travis_sample
description: A sample Flutter project that runs tests on Travis.

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
